version: '3.8'

services:
  # AI Report Application
  app:
    build: .
    container_name: ai-report-app
    restart: unless-stopped
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    command: >
      sh -c "
        echo 'Running database migrations...' &&
        npx prisma migrate deploy &&
        echo 'Starting application...' &&
        npm start
      "
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-4000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s